/**
 * 指纹注入器 v1.2
 *
 * 接收一个 BrowserProfile，在主世界（Main World）注入对应的硬件伪装代码
 * 通过 webFrame.executeJavaScript() 注入到浏览器视图
 *
 * 伪装维度：
 * - navigator.platform / languages / hardwareConcurrency / deviceMemory
 * - screen.width / height / colorDepth / pixelDepth / availWidth / availHeight
 * - WebGL vendor / renderer
 * - Canvas 微噪（±1 bit RGB 抖动）
 * - Audio 微噪（振幅偏移）
 * - 字体测量微噪
 * - mediaDevices.enumerateDevices() 伪造设备数量
 */

import type { BrowserProfile } from './profile-manager'

/**
 * 生成主世界注入的指纹伪装 JS 代码
 * 仅当 Profile 不是"真机环境"（id !== 'native'）时才注入
 */
export function buildFingerprintInjectionScript(profile: BrowserProfile): string {
  if (profile.id === 'native') {
    // 真机模式：不注入任何伪装，仅注入已有的 chrome 对象和 iframe 穿透
    return ''
  }

  const seeds = profile.autoGenerated
  const scr = profile.screen
  const wgl = profile.webgl
  const md = profile.mediaDevices

  return `
(function() {
  if (window.__watr_fp_injected) return;
  window.__watr_fp_injected = true;

  // ========== 确定性 PRNG（seeded random）==========
  function seededRandom(seed) {
    let s = seed | 0;
    return function() {
      s = (s * 1103515245 + 12345) & 0x7fffffff;
      return (s % 1000) / 1000;
    };
  }

  // ========== Navigator 属性覆写 ==========
  ${profile.platform ? `
  try {
    Object.defineProperty(navigator, 'platform', {
      get: function platform() { return ${JSON.stringify(profile.platform)}; },
      configurable: true
    });
  } catch(e) {}
  ` : ''}

  ${profile.languages.length > 0 ? `
  try {
    Object.defineProperty(navigator, 'languages', {
      get: function languages() { return ${JSON.stringify(profile.languages)}; },
      configurable: true
    });
    Object.defineProperty(navigator, 'language', {
      get: function language() { return ${JSON.stringify(profile.languages[0])}; },
      configurable: true
    });
  } catch(e) {}
  ` : ''}

  ${profile.hardwareConcurrency > 0 ? `
  try {
    Object.defineProperty(navigator, 'hardwareConcurrency', {
      get: function hardwareConcurrency() { return ${profile.hardwareConcurrency}; },
      configurable: true
    });
  } catch(e) {}
  ` : ''}

  ${profile.deviceMemory > 0 ? `
  try {
    Object.defineProperty(navigator, 'deviceMemory', {
      get: function deviceMemory() { return ${profile.deviceMemory}; },
      configurable: true
    });
  } catch(e) {}
  ` : ''}

  // ========== Screen 属性覆写 ==========
  ${scr.width > 0 ? `
  try {
    var screenProps = ${JSON.stringify({
      width: scr.width,
      height: scr.height,
      colorDepth: scr.colorDepth,
      pixelDepth: scr.pixelDepth,
      availWidth: scr.availWidth,
      availHeight: scr.availHeight
    })};
    for (var prop in screenProps) {
      (function(p, v) {
        Object.defineProperty(screen, p, {
          get: function() { return v; },
          configurable: true
        });
      })(prop, screenProps[prop]);
    }
    ${scr.devicePixelRatio > 0 ? `
    Object.defineProperty(window, 'devicePixelRatio', {
      get: function devicePixelRatio() { return ${scr.devicePixelRatio}; },
      configurable: true
    });
    ` : ''}
  } catch(e) {}
  ` : ''}

  // ========== WebGL Vendor / Renderer 伪装 ==========
  ${wgl.vendor ? `
  try {
    var origGetParam = WebGLRenderingContext.prototype.getParameter;
    WebGLRenderingContext.prototype.getParameter = function(param) {
      if (param === 37445) return ${JSON.stringify(wgl.vendor)};
      if (param === 37446) return ${JSON.stringify(wgl.renderer)};
      return origGetParam.call(this, param);
    };
    // WebGL2 同理
    if (typeof WebGL2RenderingContext !== 'undefined') {
      var origGetParam2 = WebGL2RenderingContext.prototype.getParameter;
      WebGL2RenderingContext.prototype.getParameter = function(param) {
        if (param === 37445) return ${JSON.stringify(wgl.vendor)};
        if (param === 37446) return ${JSON.stringify(wgl.renderer)};
        return origGetParam2.call(this, param);
      };
    }
  } catch(e) {}
  ` : ''}

  // ========== Canvas 微噪注入 ==========
  ${seeds.canvasNoiseSeed > 0 ? `
  try {
    var canvasRng = seededRandom(${seeds.canvasNoiseSeed});

    // 拦截 toDataURL
    var origToDataURL = HTMLCanvasElement.prototype.toDataURL;
    HTMLCanvasElement.prototype.toDataURL = function() {
      var ctx = this.getContext('2d');
      if (ctx) {
        try {
          var imgData = ctx.getImageData(0, 0, this.width, this.height);
          for (var i = 0; i < imgData.data.length; i += 4) {
            // 仅对 R 通道注入 ±1 bit 噪声
            imgData.data[i] = Math.max(0, Math.min(255, imgData.data[i] + (canvasRng() < 0.5 ? -1 : 1)));
          }
          ctx.putImageData(imgData, 0, 0);
        } catch(e) {}
      }
      return origToDataURL.apply(this, arguments);
    };

    // 拦截 toBlob
    var origToBlob = HTMLCanvasElement.prototype.toBlob;
    HTMLCanvasElement.prototype.toBlob = function() {
      var ctx = this.getContext('2d');
      if (ctx) {
        try {
          var imgData = ctx.getImageData(0, 0, this.width, this.height);
          for (var i = 0; i < imgData.data.length; i += 4) {
            imgData.data[i] = Math.max(0, Math.min(255, imgData.data[i] + (canvasRng() < 0.5 ? -1 : 1)));
          }
          ctx.putImageData(imgData, 0, 0);
        } catch(e) {}
      }
      return origToBlob.apply(this, arguments);
    };
  } catch(e) {}
  ` : ''}

  // ========== Audio 微噪注入 ==========
  ${seeds.audioNoiseSeed > 0 ? `
  try {
    var audioRng = seededRandom(${seeds.audioNoiseSeed});

    var origGetChannelData = AudioBuffer.prototype.getChannelData;
    AudioBuffer.prototype.getChannelData = function(channel) {
      var data = origGetChannelData.call(this, channel);
      // 对每个采样值注入极微小的偏移
      for (var i = 0; i < data.length; i += 100) {
        data[i] = data[i] + (audioRng() - 0.5) * 0.0001;
      }
      return data;
    };
  } catch(e) {}
  ` : ''}

  // ========== 字体测量微噪 ==========
  ${seeds.fontNoiseSeed > 0 ? `
  try {
    var fontRng = seededRandom(${seeds.fontNoiseSeed});
    var origMeasureText = CanvasRenderingContext2D.prototype.measureText;
    CanvasRenderingContext2D.prototype.measureText = function(text) {
      var metrics = origMeasureText.call(this, text);
      // 对 width 注入 ±0.001 偏移
      var origWidth = metrics.width;
      Object.defineProperty(metrics, 'width', {
        get: function() { return origWidth + (fontRng() - 0.5) * 0.002; }
      });
      return metrics;
    };
  } catch(e) {}
  ` : ''}

  // ========== MediaDevices 伪造 ==========
  ${(md.speakers > 0 || md.micros > 0) ? `
  try {
    var origEnumerate = navigator.mediaDevices.enumerateDevices;
    navigator.mediaDevices.enumerateDevices = function() {
      return origEnumerate.call(navigator.mediaDevices).then(function(devices) {
        var faked = [];
        for (var i = 0; i < ${md.micros}; i++) {
          faked.push({ deviceId: 'mic_' + i, kind: 'audioinput', label: 'Microphone ' + i, groupId: 'g' + i });
        }
        for (var j = 0; j < ${md.speakers}; j++) {
          faked.push({ deviceId: 'spk_' + j, kind: 'audiooutput', label: 'Speaker ' + j, groupId: 'g' + j });
        }
        for (var k = 0; k < ${md.webcams}; k++) {
          faked.push({ deviceId: 'cam_' + k, kind: 'videoinput', label: 'Camera ' + k, groupId: 'g' + k });
        }
        return faked;
      });
    };
  } catch(e) {}
  ` : ''}

})();
`
}
