/**
 * 浏览器环境 Profile 管理器 v1.2
 *
 * 管理指纹环境配置的 CRUD 操作：
 * - 内置"真机环境"Profile（默认，不可删除）
 * - 内置"Win10 预设"Profile（从 bot.sannysoft.com 检测数据提取）
 * - 用户自定义 Profile（可增删改）
 * - JSON 文件持久化到 portableRoot/profiles/
 */

import { promises as fs } from 'fs'
import { join } from 'path'

/** 浏览器环境配置 Profile */
export interface BrowserProfile {
  id: string
  name: string
  isBuiltin: boolean
  createdAt: string

  // ---- 可手动设置的类目 ----
  userAgent: string
  platform: string
  languages: string[]
  hardwareConcurrency: number
  deviceMemory: number

  screen: {
    width: number
    height: number
    colorDepth: number
    pixelDepth: number
    availWidth: number
    availHeight: number
    devicePixelRatio: number
  }

  webgl: {
    vendor: string
    renderer: string
  }

  mediaDevices: {
    speakers: number
    micros: number
    webcams: number
  }

  // ---- 自动变更的类目（每次启动自动生成） ----
  autoGenerated: {
    canvasNoiseSeed: number
    audioNoiseSeed: number
    webglNoiseSeed: number
    fontNoiseSeed: number
  }
}

/** 真机环境 Profile（所有值为空/0 代表直通宿主机真实硬件） */
const NATIVE_PROFILE: BrowserProfile = {
  id: 'native',
  name: '真机环境（默认）',
  isBuiltin: true,
  createdAt: '2026-01-01T00:00:00.000Z',

  userAgent: '',   // 空 = 使用真机 UA
  platform: '',    // 空 = 使用真机平台
  languages: [],   // 空 = 使用真机语言
  hardwareConcurrency: 0,  // 0 = 使用真机值
  deviceMemory: 0,

  screen: {
    width: 0, height: 0,
    colorDepth: 0, pixelDepth: 0,
    availWidth: 0, availHeight: 0,
    devicePixelRatio: 0
  },

  webgl: { vendor: '', renderer: '' },
  mediaDevices: { speakers: 0, micros: 0, webcams: 0 },

  // 真机模式不注入噪声
  autoGenerated: {
    canvasNoiseSeed: 0,
    audioNoiseSeed: 0,
    webglNoiseSeed: 0,
    fontNoiseSeed: 0
  }
}

/** Win10 预设 Profile（从 bot.sannysoft.com 检测数据提取） */
const WIN10_PRESET_PROFILE: BrowserProfile = {
  id: 'win10_preset',
  name: 'Win10 预设',
  isBuiltin: true,
  createdAt: '2026-01-01T00:00:00.000Z',

  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.7871.224 Safari/537.36',
  platform: 'Win32',
  languages: ['zh-CN', 'zh-Hans-CN'],
  hardwareConcurrency: 16,
  deviceMemory: 16,

  screen: {
    width: 1920,
    height: 1080,
    colorDepth: 24,
    pixelDepth: 24,
    availWidth: 1920,
    availHeight: 1032,
    devicePixelRatio: 1
  },

  webgl: {
    vendor: 'Google Inc. (NVIDIA)',
    renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU (0x00002520) Direct3D11 vs_5_0 ps_5_0, D3D11)'
  },

  mediaDevices: {
    speakers: 5,
    micros: 3,
    webcams: 0
  },

  // 自动变更：每次应用时重新生成
  autoGenerated: {
    canvasNoiseSeed: 0,  // 初始化时动态生成
    audioNoiseSeed: 0,
    webglNoiseSeed: 0,
    fontNoiseSeed: 0
  }
}

export class ProfileManager {
  private profilesDir: string
  private profiles: Map<string, BrowserProfile> = new Map()
  private activeProfileId: string = 'native'

  constructor(portableRoot: string) {
    this.profilesDir = join(portableRoot, 'profiles')
  }

  /** 初始化：创建目录 + 加载内置 Profile + 加载用户 Profile */
  async init(): Promise<void> {
    await fs.mkdir(this.profilesDir, { recursive: true })

    // 注册内置 Profile
    this.profiles.set(NATIVE_PROFILE.id, { ...NATIVE_PROFILE })
    this.profiles.set(WIN10_PRESET_PROFILE.id, { ...WIN10_PRESET_PROFILE })

    // 加载用户自定义 Profile
    try {
      const entries = await fs.readdir(this.profilesDir)
      for (const entry of entries) {
        if (!entry.endsWith('.json')) continue
        try {
          const raw = await fs.readFile(join(this.profilesDir, entry), 'utf-8')
          const profile: BrowserProfile = JSON.parse(raw)
          if (profile.id && !profile.isBuiltin) {
            this.profiles.set(profile.id, profile)
          }
        } catch { /* 跳过损坏的 Profile 文件 */ }
      }
    } catch { /* 目录不存在则忽略 */ }

    // 为非真机 Profile 重新生成噪声种子
    for (const [id, profile] of this.profiles) {
      if (id !== 'native') {
        profile.autoGenerated = this.generateNoiseSeeds()
      }
    }
  }

  /** 获取所有 Profile 列表 */
  listProfiles(): BrowserProfile[] {
    return Array.from(this.profiles.values())
  }

  /** 获取指定 Profile */
  getProfile(id: string): BrowserProfile | undefined {
    return this.profiles.get(id)
  }

  /** 获取当前活动 Profile */
  getActiveProfile(): BrowserProfile {
    return this.profiles.get(this.activeProfileId) || NATIVE_PROFILE
  }

  /** 获取活动 Profile ID */
  getActiveProfileId(): string {
    return this.activeProfileId
  }

  /** 设置活动 Profile */
  setActiveProfile(id: string): void {
    if (this.profiles.has(id)) {
      this.activeProfileId = id
    }
  }

  /** 获取 Win10 预设模板值（供 UI 编辑器使用） */
  getTemplateValues(): BrowserProfile {
    return { ...WIN10_PRESET_PROFILE }
  }

  /** 创建新的用户 Profile */
  async createProfile(profile: Omit<BrowserProfile, 'id' | 'isBuiltin' | 'createdAt' | 'autoGenerated'>): Promise<BrowserProfile> {
    const newProfile: BrowserProfile = {
      ...profile,
      id: `custom_${Date.now()}`,
      isBuiltin: false,
      createdAt: new Date().toISOString(),
      autoGenerated: this.generateNoiseSeeds()
    }

    this.profiles.set(newProfile.id, newProfile)
    await this.saveProfile(newProfile)
    return newProfile
  }

  /** 更新用户 Profile */
  async updateProfile(id: string, updates: Partial<BrowserProfile>): Promise<BrowserProfile | null> {
    const profile = this.profiles.get(id)
    if (!profile || profile.isBuiltin) return null

    // 合并更新（不允许修改 id, isBuiltin, autoGenerated）
    const updated: BrowserProfile = {
      ...profile,
      ...updates,
      id: profile.id,
      isBuiltin: false,
      autoGenerated: this.generateNoiseSeeds()  // 更新时重新生成噪声
    }

    this.profiles.set(id, updated)
    await this.saveProfile(updated)
    return updated
  }

  /** 删除用户 Profile */
  async deleteProfile(id: string): Promise<boolean> {
    const profile = this.profiles.get(id)
    if (!profile || profile.isBuiltin) return false

    this.profiles.delete(id)

    // 如果删除的是当前活动 Profile，切回真机
    if (this.activeProfileId === id) {
      this.activeProfileId = 'native'
    }

    try {
      await fs.unlink(join(this.profilesDir, `${id}.json`))
    } catch { /* 文件不存在则忽略 */ }

    return true
  }

  /** 持久化 Profile 到磁盘 */
  private async saveProfile(profile: BrowserProfile): Promise<void> {
    const filePath = join(this.profilesDir, `${profile.id}.json`)
    await fs.writeFile(filePath, JSON.stringify(profile, null, 2), 'utf-8')
  }

  /** 生成随机噪声种子（每次启动/应用时自动生成） */
  private generateNoiseSeeds() {
    return {
      canvasNoiseSeed: Math.floor(Math.random() * 2147483647),
      audioNoiseSeed: Math.floor(Math.random() * 2147483647),
      webglNoiseSeed: Math.floor(Math.random() * 2147483647),
      fontNoiseSeed: Math.floor(Math.random() * 2147483647)
    }
  }
}
